import { Component } from '@angular/core';

interface CookieSection { title: string; paragraphs: string[]; items?: string[]; }

@Component({ selector: 'app-cookie-policy', templateUrl: './cookie-policy.component.html', styleUrls: ['./cookie-policy.component.css'] })
export class CookiePolicyComponent {
  readonly sections: CookieSection[] = [
    { title: 'What this policy covers', paragraphs: ['This Cookie Policy explains how PICK2WIN uses cookies and similar technologies, including your browser&rsquo;s local storage, on our website and platform. It should be read together with our <a href="/policy">Privacy Policy</a>.'] },
    { title: 'What cookies and local storage are', paragraphs: ['Cookies are small text files stored on your device by a website. Local storage is a similar browser technology that allows websites to store small amounts of information on your device. These technologies help the platform remember information between page loads and sessions, such as your sign-in status and platform preferences.'] },
    { title: 'How we use them', paragraphs: ['We use cookies and local storage only for essential purposes, including:', 'We do not use cookies or local storage to build advertising profiles or track you across other websites.'], items: ['Keeping you signed in', 'Maintaining your session', 'Remembering your in-session configuration and preferences', 'Protecting the platform against fraud, abuse, and unauthorized access', 'Supporting platform functionality and security'] },
    { title: 'Strictly necessary technologies', paragraphs: ['These technologies are required for the platform to operate properly and include:', 'Because these technologies are essential to providing the service, they cannot be disabled through our platform.'], items: ['User authentication and sign-in', 'Session management', 'Security and fraud prevention', 'In-session state and configuration management', 'Platform functionality and performance'] },
    { title: 'Local storage', paragraphs: ['In addition to cookies, PICK2WIN uses browser local storage to maintain sign-in status and remember in-session platform state. Information stored in local storage remains on your device and is used solely for operating and securing the service. We do not share local storage data with advertisers or advertising networks.'] },
    { title: 'No advertising or cross-site tracking', paragraphs: ['PICK2WIN does not use:', 'We do not sell your personal information to advertisers.'], items: ['Advertising cookies', 'Third-party advertising trackers', 'Cross-site tracking technologies', 'Behavioural advertising technologies'] },
    { title: 'Third-party services', paragraphs: ['Certain third-party service providers may place their own cookies when providing services to us. For example, payment processing is provided by <strong>Razorpay</strong>. During payment or checkout, Razorpay may use cookies and similar technologies for security, fraud prevention, authentication, and payment processing. Such technologies are governed by the applicable policies of the respective provider. Aside from payment processing and essential service delivery, PICK2WIN does not use third-party advertising or marketing cookies.'] },
    { title: 'Managing cookies', paragraphs: ['Most web browsers allow you to:', 'Please note that disabling or removing essential cookies or local storage may prevent you from signing in, completing purchases, generating teams, or using parts of the platform properly.'], items: ['View stored cookies', 'Delete cookies', 'Block cookies', 'Clear local storage'] },
    { title: 'Consent and changes', paragraphs: ['PICK2WIN uses only essential cookies and local storage that are necessary for the operation and security of the platform. Where applicable law requires consent for any future non-essential technologies, we will obtain your consent before they are used. We may update this Cookie Policy from time to time. Any updates will be published on this page and reflected by the “Last Updated” date above.'] },
    { title: 'Contact us', paragraphs: ['If you have any questions about this Cookie Policy, please contact us:<br>Email: <a href="mailto:support@pick2win.io">support@pick2win.io</a>'] }
  ];
}
